# Generated by Django 2.2.3 on 2019-11-07 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20191106_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 17, 13, 41, 305849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 17, 13, 41, 305849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 17, 13, 41, 304852, tzinfo=utc)),
        ),
    ]
