# Generated by Django 2.2.3 on 2019-11-18 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20191118_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='logo/bestanaliz.png', upload_to=mainApp.models.upload_to_directory),
        ),
        migrations.AlterField(
            model_name='forumrules',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 14, 12, 59, 953095, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 14, 12, 59, 952069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 14, 12, 59, 952069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 18, 14, 12, 59, 951099, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='logo/bestanaliz.png', upload_to=mainApp.models.upload_to_directory),
        ),
    ]
