# Generated by Django 2.2.3 on 2019-11-07 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20191107_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 19, 19, 16, 778248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 19, 19, 16, 778248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 19, 19, 16, 777251, tzinfo=utc)),
        ),
    ]
