# Generated by Django 2.2.3 on 2019-11-27 12:57

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20191118_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_edit',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='which_admin_edit',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='forumrules',
            name='text',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='forumrules',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 12, 57, 55, 482143, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 12, 57, 55, 482143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 12, 57, 55, 482143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 12, 57, 55, 478055, tzinfo=utc)),
        ),
    ]
