# Generated by Django 2.2.3 on 2019-11-27 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20191127_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='admin_edit',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='which_admin_edit',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='forumrules',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 13, 27, 21, 511824, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 13, 27, 21, 506554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 13, 27, 21, 506554, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 13, 27, 21, 498375, tzinfo=utc)),
        ),
    ]
