# Generated by Django 2.2.3 on 2019-11-08 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20191107_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=mainApp.models.upload_to_directory),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=mainApp.models.upload_to_directory),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='likecomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 11, 58, 53, 939326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 11, 58, 53, 939326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 11, 58, 53, 939326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
