# Generated by Django 2.2.3 on 2019-10-28 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_userprofile_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 28, 22, 53, 19, 902453)),
        ),
    ]
