# Generated by Django 2.2.3 on 2019-10-29 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20191029_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 29, 19, 29, 35, 148604)),
        ),
    ]
