# Generated by Django 2.2.3 on 2019-10-29 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20191029_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 29, 22, 49, 10, 538159)),
        ),
    ]
