# Generated by Django 2.2.3 on 2019-10-30 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_auto_20191029_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 21, 30, 12, 413986)),
        ),
    ]
