# Generated by Django 2.2.3 on 2019-10-30 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_auto_20191030_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 22, 39, 20, 124089)),
        ),
    ]
