# Generated by Django 2.2.3 on 2019-10-30 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_auto_20191030_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 30, 23, 33, 12, 232200)),
        ),
    ]
