# Generated by Django 2.2.3 on 2019-10-30 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_auto_20191031_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 0, 49, 48, 37181)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.Ranks'),
        ),
    ]
