# Generated by Django 2.2.3 on 2019-10-30 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0015_auto_20191031_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranks',
            name='del_comments_perm',
            field=models.BooleanField(default=0, verbose_name='Mesaj Silme (Başkasının)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 1, 30, 50, 265554)),
        ),
    ]
