# Generated by Django 2.2.3 on 2019-10-31 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0016_auto_20191031_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 11, 21, 29, 576145)),
        ),
    ]
