# Generated by Django 2.2.3 on 2019-10-31 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0018_auto_20191031_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 10, 31, 22, 35, 35, 683904)),
        ),
    ]
