# Generated by Django 2.2.3 on 2019-10-31 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0019_auto_20191031_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranks',
            name='edit_post_perm',
            field=models.BooleanField(default=0, verbose_name='Konu Düzenleme (Başkasının)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 1, 0, 4, 20, 8484)),
        ),
    ]
