# Generated by Django 2.2.3 on 2019-11-02 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0023_auto_20191102_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='channel',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 18, 52, 35, 324819)),
        ),
    ]
