# Generated by Django 2.2.3 on 2019-11-02 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0024_auto_20191102_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='userApp.Channel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 2, 18, 54, 24, 714394)),
        ),
    ]
