# Generated by Django 2.2.3 on 2019-11-03 11:45

import datetime
from django.db import migrations, models
import userApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0029_auto_20191102_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 3, 14, 45, 15, 220661)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='default-pp.png', upload_to=userApp.models.upload_to_directory),
        ),
    ]
