# Generated by Django 2.2.3 on 2019-11-05 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0031_auto_20191103_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 23, 57, 58, 886435)),
        ),
    ]
