# Generated by Django 2.2.3 on 2019-11-06 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0032_auto_20191105_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 15, 13, 56, 267451)),
        ),
    ]
