# Generated by Django 2.2.3 on 2019-11-06 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0033_auto_20191106_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 6, 18, 19, 18, 103350)),
        ),
    ]
