# Generated by Django 2.2.3 on 2019-11-07 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0034_auto_20191106_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 7, 20, 13, 41, 307379)),
        ),
    ]
