# Generated by Django 2.2.3 on 2019-11-07 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0036_auto_20191107_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='new_message',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 7, 22, 23, 51, 531451)),
        ),
    ]
