# Generated by Django 2.2.3 on 2019-11-08 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0037_auto_20191107_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 8, 14, 58, 53, 939326)),
        ),
    ]
