# Generated by Django 2.2.3 on 2019-11-10 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0039_auto_20191111_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranks',
            name='category_perm',
        ),
        migrations.RemoveField(
            model_name='ranks',
            name='color_text_perm',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 11, 0, 34, 19, 869580)),
        ),
    ]
