# Generated by Django 2.2.3 on 2019-11-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0040_auto_20191111_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 15, 24, 8, 810060)),
        ),
    ]
