# Generated by Django 2.2.3 on 2019-11-18 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0041_auto_20191118_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 16, 32, 47, 786945)),
        ),
    ]
