# Generated by Django 2.2.3 on 2019-11-27 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0044_auto_20191118_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yeni Üye'), (2, 'Kıdemli Üye'), (3, 'Özel Üye'), (4, 'Moderatör'), (5, 'Büro Destek'), (6, 'Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_day',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 15, 57, 55, 487479)),
        ),
    ]
